---
- name: Install apache
  yum:
    name: "{{ httpd_package }}"
    state: present

- name: Start and enable apache
  systemd:
    name: "{{ httpd_service }}"
    state: started
    enabled: true

- name: Put index.html
  template:
    src: index.html.j2
    dest: "{{ httpd_index_path }}"
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"
    mode: "{{ httpd_mode }}"

- name: Install firewalld
  yum:
    name: firewalld
    state: present

- name: Set firewall policy
  firewalld:
    zone: public
    port: "{{ httpd_port }}/tcp"
    permanent: true
    state: enabled
  register: _httpd_firewalld_result

- name: Restart firewalld
  systemd:
    name: firewalld.service
    state: restarted
  when: _httpd_firewalld_result.changed
  tags:
    - skip_ansible_lint
